[tool.poetry]
name = "example"
version = "0.1.2"
description = ""
authors = ["po3rin"]

[tool.poetry.dependencies]
python = "^3.9"
esguard = "^0.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
